version: '3.8'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: hw2/nginx
    container_name: webserver2
    ports:
      - "80:80"
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: hw2/php 
    container_name: hw2 
    volumes:
      - ./code:/data/mysite.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge